### PR TITLE
Fix repeating subscriptions

### PR DESCRIPTION
**Pull request by magicjohnson**
do not repeat subscriptions with the same callback url

### CODE REVIEW

**Comment by adamkerz** [comment]
Just quickly reviewed this, will look in more detail later tonight, but I wanted to mention that the WebSub standard says that re-subscribing with the same url again is meant to update the timeout, if the subscriber provided one. Or, I guess, add the default timeout on to now and set it to that if they didn't?

**Review by koriaf — APPROVED** [review]

**Comment by koriaf** [comment]
updating expiration time to:
* if new exp value provided - to the new value
* if new exp value is not provided - to max (old_exp_time, current + default)

looks logical to me.

**Comment by magicjohnson** [comment]
just read that hub must not issue perpetual lease durations. So the question is who sets the default expiration value? I would let the actual hub implementation (node/channel) to do that

**Comment by adamkerz** [comment]
Yes, it should use a default (let's start with 5 days) if none is provided by the subscriber (ie. expiration isn't required) or if the subscriber requests a longer value. If the subscriber re-subscribes, the expiration should be extended by up to the default, or less if the subscriber requested a shorter time period.

**Pull request merged**
